services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - postgres

  postgres:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
